export default [
  'all',
  'videos',
  'artisanvideos',
  'gaming',
  'Documentaries',
  'cookingvideos',
  'instant_regret',
  'listentothis',
  'youtubehaiku',
  'mealtimevideos',
  'trailers',
  'movies',
  'television',
  'skateboarding',
];
